### ISSUE TITLE
Create the Design in Figma

### ISSUE THREAD

**Issue by 0m3ga13** [202306-NEA-DZ-FEW/student-store-team-2#7]
Inspirations:

[BorrowMe](https://www.borrowme.com/)

[Stooch - Discover the student world.](https://www.stooch.co/)

[Catalog Website](https://theme-stall.com/catalog-photostock/)

[MiniStore ](https://templatesjungle.com/downloads/ministore-free-ecommerce-store-bootstrap-5-website-template/)

**Comment by medshk** [comment]
Link to design assets : https://www.figma.com/file/FYZIsFvg1rLu50UnriUN8Y/Student-Store-Project?type=design&node-id=0-1&mode=design&t=KIfUe95XnbE3crKJ-0
